"""add_sprint_member_performances

Revision ID: 2351b195bdc5
Revises: 333e874b0ca5
Create Date: 2026-03-12 20:14:47.096836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2351b195bdc5'
down_revision: Union[str, None] = '333e874b0ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_member_performances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sprint_id', sa.UUID(), nullable=False, comment='Sprint this record belongs to'),
    sa.Column('github_login', sa.String(length=255), nullable=False, comment='GitHub username of the team member'),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_additions', sa.Integer(), nullable=False, comment='Lines added across all commits'),
    sa.Column('total_deletions', sa.Integer(), nullable=False, comment='Lines deleted across all commits'),
    sa.Column('active_days', sa.Integer(), nullable=False, comment='Number of distinct days with at least one commit'),
    sa.Column('workload_share', sa.Float(), nullable=False, comment='Fraction of total team commits (0-1)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprint_member_performances_sprint_id'), 'sprint_member_performances', ['sprint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sprint_member_performances_sprint_id'), table_name='sprint_member_performances')
    op.drop_table('sprint_member_performances')
    # ### end Alembic commands ###
