"""add_user_id_and_working_days_to_sprints

Revision ID: 333e874b0ca5
Revises: 99d299276cf8
Create Date: 2026-03-12 20:12:41.071914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333e874b0ca5'
down_revision: Union[str, None] = '99d299276cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of this sprint analysis session'))
    op.add_column('sprints', sa.Column('total_working_days', sa.Integer(), nullable=True, comment='Working days in the sprint (weekends + holidays excluded)'))
    op.create_index(op.f('ix_sprints_user_id'), 'sprints', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sprints', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.drop_index(op.f('ix_sprints_user_id'), table_name='sprints')
    op.drop_column('sprints', 'total_working_days')
    op.drop_column('sprints', 'user_id')
    # ### end Alembic commands ###
