"""add_soft_delete_to_sprints

Revision ID: 67ab13989207
Revises: 2351b195bdc5
Create Date: 2026-03-12 20:20:47.316370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ab13989207'
down_revision: Union[str, None] = '2351b195bdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp — null means active, set means deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'deleted_at')
    # ### end Alembic commands ###
