"""initial_tables

Revision ID: 99d299276cf8
Revises: 
Create Date: 2026-03-12 15:30:10.731790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d299276cf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_url', sa.String(length=512), nullable=False, comment='GitHub repository URL to analyse'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Sprint start date (inclusive)'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Sprint end date / deadline (inclusive)'),
    sa.Column('team_members', postgresql.ARRAY(sa.String()), nullable=True, comment='GitHub usernames of team members to track'),
    sa.Column('country_code', sa.String(length=2), nullable=False, comment='ISO 3166-1 alpha-2 country code for public holiday lookups'),
    sa.Column('performance_score', sa.Float(), nullable=True, comment='Normalised 0-100 performance score, set after analysis'),
    sa.Column('workload_balance_score', sa.Float(), nullable=True, comment='Normalised 0-100 workload balance score, set after analysis'),
    sa.Column('analysis_notes', sa.Text(), nullable=True, comment='Human-readable summary from the analysis engine'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_id'), 'sprints', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's unique email address (used as login identifier)"),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Display name'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hashed password — plain-text is never stored'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive users cannot log in'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superusers have access to admin endpoints'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sprints_id'), table_name='sprints')
    op.drop_table('sprints')
    # ### end Alembic commands ###
