"""ilk_kurulum

Revision ID: b552f7a27c31
Revises: 
Create Date: 2026-05-01 20:33:39.845582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b552f7a27c31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's unique email address (used as login identifier)"),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Display name'),
    sa.Column('github_username', sa.String(length=255), nullable=True, comment='GitHub username for fetching developer stats'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hashed password — plain-text is never stored'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive users cannot log in'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superusers have access to admin endpoints'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('project_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of this project plan'),
    sa.Column('project_idea', sa.String(), nullable=False, comment='The original project idea/goal provided by the user'),
    sa.Column('sprint_count', sa.Integer(), nullable=False, comment='Number of sprints requested'),
    sa.Column('team_members', postgresql.ARRAY(sa.String()), nullable=False, comment='GitHub usernames involved in the plan'),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The structured JSON output produced by the LLM containing sprint assignments'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_plans_id'), 'project_plans', ['id'], unique=False)
    op.create_index(op.f('ix_project_plans_user_id'), 'project_plans', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Project name'),
    sa.Column('description', sa.String(), nullable=True, comment='Project description'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='User who owns this project'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of this sprint analysis session'),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='Project this sprint belongs to'),
    sa.Column('github_url', sa.String(length=512), nullable=False, comment='GitHub repository URL to analyse'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Sprint start date (inclusive)'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Sprint end date / deadline (inclusive)'),
    sa.Column('team_members', postgresql.ARRAY(sa.String()), nullable=True, comment='GitHub usernames of team members to track'),
    sa.Column('country_code', sa.String(length=2), nullable=False, comment='ISO 3166-1 alpha-2 country code for public holiday lookups'),
    sa.Column('performance_score', sa.Float(), nullable=True, comment='Normalised 0-100 performance score, set after analysis'),
    sa.Column('workload_balance_score', sa.Float(), nullable=True, comment='Normalised 0-100 workload balance score, set after analysis'),
    sa.Column('total_working_days', sa.Integer(), nullable=True, comment='Working days in the sprint (weekends + holidays excluded)'),
    sa.Column('analysis_notes', sa.Text(), nullable=True, comment='Human-readable summary from the analysis engine'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp — null means active, set means deleted'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_id'), 'sprints', ['id'], unique=False)
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_index(op.f('ix_sprints_user_id'), 'sprints', ['user_id'], unique=False)
    op.create_table('sprint_member_performances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sprint_id', sa.UUID(), nullable=False, comment='Sprint this record belongs to'),
    sa.Column('github_login', sa.String(length=255), nullable=False, comment='GitHub username of the team member'),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_additions', sa.Integer(), nullable=False, comment='Lines added across all commits'),
    sa.Column('total_deletions', sa.Integer(), nullable=False, comment='Lines deleted across all commits'),
    sa.Column('active_days', sa.Integer(), nullable=False, comment='Number of distinct days with at least one commit'),
    sa.Column('workload_share', sa.Float(), nullable=False, comment='Fraction of total team commits (0-1)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprint_member_performances_sprint_id'), 'sprint_member_performances', ['sprint_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Task title / headline'),
    sa.Column('description', sa.String(), nullable=True, comment='Task detailed description'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current status: pending, in_progress, completed, delayed'),
    sa.Column('nlp_complexity_score', sa.Float(), nullable=False, comment='NLP calculated task complexity score (1.0 to 5.0)'),
    sa.Column('deadline', sa.Date(), nullable=True, comment='Target completion date'),
    sa.Column('sprint_id', sa.UUID(), nullable=False, comment='The sprint this task belongs to'),
    sa.Column('assignee_id', sa.UUID(), nullable=True, comment='The user assigned to this task'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_sprint_id'), 'tasks', ['sprint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_sprint_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sprint_member_performances_sprint_id'), table_name='sprint_member_performances')
    op.drop_table('sprint_member_performances')
    op.drop_index(op.f('ix_sprints_user_id'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_plans_user_id'), table_name='project_plans')
    op.drop_index(op.f('ix_project_plans_id'), table_name='project_plans')
    op.drop_table('project_plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
